apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: hacbs-jvm-operator
resources:
  - system-config.yaml

patchesStrategicMerge:
  #note that when updating the ref here you must also update system-config.yaml
  - https://raw.githubusercontent.com/redhat-appstudio/jvm-build-service-builder-images/f0c0dbbd5926e7a38af245b4e48a38ddd2d17359/image-config.yaml
