---
apiVersion: jvmbuildservice.io/v1alpha1
kind: SystemConfig
metadata:
  name: cluster
spec:
  builders:
    jdk8:
      image: quay.io/redhat-appstudio/hacbs-jdk8-builder:a0495dac30396027babf6bc4090e88ba44b12a17
      priority: 3000
    jdk11:
      image: quay.io/redhat-appstudio/hacbs-jdk11-builder:a0495dac30396027babf6bc4090e88ba44b12a17
      priority: 2000
    jdk17:
      image: quay.io/redhat-appstudio/hacbs-jdk17-builder:a0495dac30396027babf6bc4090e88ba44b12a17
      priority: 1000
    jdk7:
      image: quay.io/redhat-appstudio/hacbs-jdk7-builder:a0495dac30396027babf6bc4090e88ba44b12a17
      priority: 500
