---
apiVersion: jvmbuildservice.io/v1alpha1
kind: SystemConfig
metadata:
  name: cluster
spec:
  builders:
    jdk8:
      image: quay.io/redhat-appstudio/hacbs-jdk8-builder:99f406015228f9f77f2a0cfb687b95c04951c368
      priority: 3000
    jdk11:
      image: quay.io/redhat-appstudio/hacbs-jdk11-builder:99f406015228f9f77f2a0cfb687b95c04951c368
      priority: 2000
    jdk17:
      image: quay.io/redhat-appstudio/hacbs-jdk17-builder:99f406015228f9f77f2a0cfb687b95c04951c368
      priority: 1000
    jdk7:
      image: quay.io/redhat-appstudio/hacbs-jdk7-builder:99f406015228f9f77f2a0cfb687b95c04951c368
      priority: 500
