apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: jvm-build-service
spec:
  reference:
    workspace:
      exportName: jvm-build-service
  permissionClaims:
    - group: ""
      resource: "secrets"
      state: "Accepted"
    - group: ""
      resource: "configmaps"
      state: "Accepted"
    - group: ""
      resource: "events"
      state: "Accepted"
    - group: ""
      resource: "resourcequotas"
      state: "Accepted"
    - group: "tekton.dev"
      resource: "pipelineruns"
      # replace by pipeline-service identityHash
      identityHash: pipeline-service
      state: "Accepted"
