apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: jvm-build-service
spec:
  reference:
    workspace:
      exportName: jvm-build-service
  permissionClaims:
    - group: ""
      resource: "secrets"
      state: "Accepted"
    - group: ""
      resource: "configmaps"
      state: "Accepted"
    - group: ""
      resource: "serviceaccounts"
      state: "Accepted"
    - group: ""
      resource: "events"
      state: "Accepted"
    - group: ""
      resource: "services"
      # replace by pipeline-service identityHash, though most likely creation of the artifact-cache will have to move out of the controller
      identityHash: pipeline-service
      state: "Accepted"
    - group: "apps"
      resource: "deployments"
      # replace by pipeline-service identityHash, though most likely creation of the artifact-cache will have to move out of the controller
      identityHash: pipeline-service
      state: "Accepted"
    - group: "tekton.dev"
      resource: "pipelineruns"
      # replace by pipeline-service identityHash
      identityHash: pipeline-service
      state: "Accepted"
