---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jvm-build-config
data:
  redirect-artifact-quarkus: "io.quarkus:(.*):2\\.7\\\\..*=io.quarkus:$1:2.7.5.Final-redhat-00011"
  cache-image: jvm-build-service-cache-image:dev
