apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: jvm-build-service
spec:
  selector:
    matchLabels:
      app: localstack
  replicas: 1
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:0.11.5
          ports:
            # exposing s3
            - containerPort: 4572
          env:
            - name: SERVICES
              value: "s3:4572"
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: jvm-build-service
spec:
  selector:
    app: localstack
  ports:
    - port: 4572
      protocol: TCP
      name: s3
  type: LoadBalancer
