apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kcp-jvm-build-service-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kcp-jvm-build-service-role
subjects:
  - kind: ServiceAccount
    name: hacbs-jvm-operator
    namespace: jvm-build-service
