apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: jenkins-build-
spec:
  pipelineRef:
    name: sample-component-build
  params:
    - name: url
      value: https://github.com/jenkinsci/jenkins.git
    - name: app-path
      value: war/target
    - name: revision
      value: jenkins-2.368
  workspaces:
    - name: maven-settings
      emptyDir: {}
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 5Gi
  taskRunSpecs:
    - pipelineTaskName: maven-run
      taskServiceAccountName: pipeline

