apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: jctools-build-
spec:
  taskRef:
    name: run-maven-component-build
    kind: ClusterTask
  params:
    - name: URL
      value: https://github.com/JCTools/JCTools.git
    - name: TAG
      value: v3.3.0
    - name: IMAGE
      value: quay.io/sdouglas/hacbs-jdk11-builder:test
    - name: ENFORCE_VERSION
      value: 3.3.0
  workspaces:
    - name: maven-settings
      emptyDir: {}
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 1Gi
