apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: sample-discovery-build-
spec:
  taskRef:
    name: create-component-builds
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 1Gi
  serviceAccountName: hacbs-jvm-operator
