apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: sample-component-build-
spec:
  pipelineRef:
    name: sample-component-build
  params:
    - name: url
      value: https://github.com/stuartwdouglas/hacbs-test-project
    - name: revision
      value: a2dc78fcc71f7d735a29f6f1715ae2aa41ee2856
  workspaces:
    - name: maven-settings
      emptyDir: {}
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 1Gi
  serviceAccountNames:
    - serviceAccountName: pipeline
      taskName: maven-run
