apiVersion: jvmbuildservice.io/v1alpha1
kind: ArtifactBuild
metadata:
  annotations:
    jvmbuildservice.io/contaminated-e26f2955830ae268e2b0: bf3faa469efdd1de517438465de5200e
  name: commons.lang3.3.5-0612ad3b
  namespace: test-jvm-namespace
spec:
  gav: org.apache.commons:commons-lang3:3.5
