apiVersion: jvmbuildservice.io/v1alpha1
kind: ArtifactBuild
metadata:
  name: jakarta.annotation.api.1.3.5-adb3e708
  namespace: test-jvm-namespace
spec:
  gav: jakarta.annotation:jakarta.annotation-api:1.3.5
