apiVersion: jvmbuildservice.io/v1alpha1
kind: ArtifactBuild
metadata:
  name: jboss.logging.3.4.3.final-c6139dd5
  namespace: test-jvm-namespace
spec:
  gav: org.jboss.logging:jboss-logging:3.4.3.Final
