apiVersion: jvmbuildservice.io/v1alpha1
kind: ArtifactBuild
metadata:
  name: quarkus.scheduler.2.7.6.final-5ddd1a05
  namespace: test-jvm-namespace
spec:
  gav: io.quarkus:quarkus-scheduler:2.7.6.Final
