apiVersion: jvmbuildservice.io/v1alpha1
kind: ArtifactBuild
metadata:
  name: quarkus.smallrye.health.2.7.6.final-03aefae2
  namespace: test-jvm-namespace
spec:
  gav: io.quarkus:quarkus-smallrye-health:2.7.6.Final
