apiVersion: jvmbuildservice.io/v1alpha1
kind: ArtifactBuild
metadata:
  name: smallrye.mutiny.vertx.runtime.2.21.0-1b76159f
  namespace: test-jvm-namespace
spec:
  gav: io.smallrye.reactive:smallrye-mutiny-vertx-runtime:2.21.0
