apiVersion: jvmbuildservice.io/v1alpha1
kind: ArtifactBuild
metadata:
  name: smallrye.mutiny.vertx.web.common.2.21.0-6394554b
  namespace: test-jvm-namespace
spec:
  gav: io.smallrye.reactive:smallrye-mutiny-vertx-web-common:2.21.0
