apiVersion: jvmbuildservice.io/v1alpha1
kind: ArtifactBuild
metadata:
  name: smallrye.config.common.2.9.2-688371d8
  namespace: test-jvm-namespace
spec:
  gav: io.smallrye.config:smallrye-config-common:2.9.2
