apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: lookup-build-info
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
spec:
  description: >-
    This Task is used to find build specific information.
  params:
    - name: BUILD_IMAGE
      type: string
      description: >-
        The image to use for dependency analysis.
      default: "quay.io/sdouglas/hacbs-jvm-build-request-processor:dev"
    - name: RECIPE_DATABASE
      type: string
      description: >-
        The git recipe database.
      default: "https://github.com/stuartwdouglas/tempdata2.git"
    - name: SCM_URL
      type: string
      description: >-
        The SCM URL
    - name: TAG
      type: string
      description: >-
        The SCM TAG
    - name: CONTEXT
      type: string
      description: >-
        The path to the build inside the repo
    - name: VERSION
      type: string
      description: >-
        The version of the build
  results:
    - name: message
      description: A failure message
    - name: build-info
      description: The JSON build recipe
  steps:
    - name: process-build-requests
      image: $(params.BUILD_IMAGE)
      args:
        - lookup-build-info
        - --recipes
        - $(params.RECIPE_DATABASE)
        - --scm-url
        - $(params.SCM_URL)
        - --scm-tag
        - $(params.TAG)
        - --context
        - $(params.CONTEXT)
        - --version
        - $(params.VERSION)
        - --message
        - $(results.message.path)
        - --build-info
        - $(results.build-info.path)