---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: jvm-build-service
