apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../../base"
  - "../../cache/overlays/production"
  - "../../operator/overlays/production"

images:
  - name: hacbs-jvm-cache
    newName: quay.io/goldmann/hacbs-jvm-cache
    newTag: dev
