apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
 - name: hacbs-jvm-sidecar
 - newName: quay.io/appstudio-local/hacbs-jvm-sidecar:dev

bases:
 - "../../base"
 - "../../cache/overlays/local"
 - "../../operator/overlays/local"

patches:
 - patch: |-
     - op: replace
       path: /spec/sidecars/0/imagePullPolicy
       value: Never
   target:
     kind: Task
     name: maven
 - patch: |-
     - op: replace
       path: /spec/sidecars/0/image
       value: quay.io/appstudio-local/hacbs-jvm-sidecar:dev
   target:
    kind: Task
    name: maven
