apiVersion: apps/v1
kind: Deployment
metadata:
  name: hacbs-jvm-operator
  namespace: jvm-build-service
spec:
  template:
    spec:
      containers:
        - name: hacbs-jvm-operator
          env:
            - name: JVM_BUILD_SERVICE_REQPROCESSOR_IMAGE
              value: jvm-build-service-reqprocessor-image
            - name: JVM_BUILD_SERVICE_SIDECAR_IMAGE
              value: jvm-build-service-sidecar-image
