apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: hacbs-jvm-operator
resources:
  - components.hacbs.redhat.com-v1.yml
  - deployment.yaml
  - sa.yaml
  - rbac.yaml
