apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: hacbs-jvm-operator
resources:
  - jvmbuildservice.io_artifactbuildrequests.yaml
  - jvmbuildservice.io_dependencybuilds.yaml
  - deployment.yaml
  - sa.yaml
  - rbac.yaml
