apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hacbs-jvm-operator
rules:
  - apiGroups:
      - hacbs.redhat.com
    resources:
      - components
      - components/status
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hacbs-jvm-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hacbs-jvm-operator
subjects:
  - kind: ServiceAccount
    name: hacbs-jvm-operator
    namespace: default
