---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hacbs-jvm-cache
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - taskruns/status
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hacbs-jvm-cache-{{ .Values.kcpNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hacbs-jvm-cache
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: {{ .Values.kcpNamespace }}

