# Adds namespace to all resources.... HAS on KCP had this ... not sure yet how it translates, need to examine infra-deploy preview mode
#namespace: jvm-build-service-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
#namePrefix: application-service-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

bases:
  - ../operator/base
  - ../operator/config
  - ../kcp-rbac

#patches:
  # HAS on KCP says it needs to use default service account name right now; going to try without that first
  # but leave this bit commented out for reference, potential re-add
  #- patch: |-
  #    - op: replace
  #      path: /spec/template/spec/serviceAccountName
  #      value: default
  #  target:
  #    kind: Deployment
  #    name: hacbs-jvm-operator
