apiVersion: apps/v1
kind: Deployment
metadata:
  name: jvm-build-workspace-artifact-cache
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jvm-build-workspace-artifact-cache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jvm-build-workspace-artifact-cache
    spec:
      containers:
      - env:
        - name: CACHE_PATH
          value: /cache
        - name: QUARKUS_VERTX_EVENT_LOOPS_POOL_SIZE
          value: "4"
        - name: QUARKUS_THREAD_POOL_MAX_THREADS
          value: "50"
        - name: REGISTRY_OWNER
          value: {{ .Values.quayTestRepoOwner }}
        - name: REGISTRY_HOST
          value: quay.io
        - name: REGISTRY_REPOSITORY
          value: test-images
        - name: REGISTRY_INSECURE
          value: "false"
        - name: REGISTRY_PREPEND_TAG
          value: "{{ .Values.prependTag }}"
        - name: REGISTRY_TOKEN
          valueFrom:
            secretKeyRef:
              key: registry.token
              name: jvm-build-secrets
        - name: BUILD_POLICY_DEFAULT_RELOCATION_PATTERN
          value: (io.github.stuartwdouglas.hacbs-test.simple):(simple-jdk17):(99-does-not-exist)=io.github.stuartwdouglas.hacbs-test.simple:simple-jdk17:0.1.2
        - name: STORE_ECLIPSELINK_URL
          value: https://download.eclipse.org/rt/eclipselink/maven.repo
        - name: STORE_ECLIPSELINK_TYPE
          value: maven2
        - name: STORE_GRADLE_URL
          value: https://repo.gradle.org/artifactory/libs-releases
        - name: STORE_GRADLE_TYPE
          value: maven2
        - name: STORE_KOTLINNATIVE14LINUX_URL
          value: https://download.jetbrains.com/kotlin/native/builds/releases/1.4/linux
        - name: STORE_KOTLINNATIVE14LINUX_TYPE
          value: maven2
        - name: STORE_AJOBERSTAR_URL
          value: https://ajoberstar.org/bintray-backup
        - name: STORE_AJOBERSTAR_TYPE
          value: maven2
        - name: STORE_GOOGLEANDROID_URL
          value: https://dl.google.com/dl/android/maven2/
        - name: STORE_GOOGLEANDROID_TYPE
          value: maven2
        - name: STORE_CONFLUENT_URL
          value: https://packages.confluent.io/maven
        - name: STORE_CONFLUENT_TYPE
          value: maven2
        - name: STORE_REDHAT_URL
          value: https://maven.repository.redhat.com/ga
        - name: STORE_REDHAT_TYPE
          value: maven2
        - name: STORE_SPRING_PLUGINS_URL
          value: https://repo.springsource.org/plugins-release
        - name: STORE_SPRING_PLUGINS_TYPE
          value: maven2
        - name: STORE_JSWEET_URL
          value: https://repository.jsweet.org/artifactory/libs-release-local
        - name: STORE_JSWEET_TYPE
          value: maven2
        - name: STORE_JITPACK_URL
          value: https://jitpack.io
        - name: STORE_JITPACK_TYPE
          value: maven2
        - name: STORE_JCS_URL
          value: https://packages.jetbrains.team/maven/p/jcs/maven
        - name: STORE_JCS_TYPE
          value: maven2
        - name: STORE_DOKKADEV_URL
          value: https://maven.pkg.jetbrains.space/kotlin/p/dokka/dev
        - name: STORE_DOKKADEV_TYPE
          value: maven2
        - name: STORE_GRADLEPLUGINS_URL
          value: https://plugins.gradle.org/m2
        - name: STORE_GRADLEPLUGINS_TYPE
          value: maven2
        - name: STORE_JBOSS_URL
          value: https://repository.jboss.org/nexus/content/groups/public/
        - name: STORE_JBOSS_TYPE
          value: maven2
        - name: STORE_JENKINS_URL
          value: https://repo.jenkins-ci.org/public/
        - name: STORE_JENKINS_TYPE
          value: maven2
        - name: BUILD_POLICY_DEFAULT_STORE_LIST
          value: rebuilt,central,jboss,gradleplugins,confluent,gradle,eclipselink,redhat,jitpack,jsweet,jenkins,spring-plugins,dokkadev,ajoberstar,googleandroid,kotlinnative14linux,jcs
        image: quay.io/{{ .Values.quayJvmBuildServiceRepo }}/hacbs-jvm-cache:{{ .Values.quayJvmBuildServiceTag }}
        imagePullPolicy: Always
        name: jvm-build-workspace-artifact-cache
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "4"
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 3Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cache
          name: jvm-build-workspace-artifact-cache
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: pipeline
      serviceAccountName: pipeline
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          sizeLimit: 10Gi
        name: jvm-build-workspace-artifact-cache

