apiVersion: v1
kind: Secret
metadata:
  name: jvm-build-secrets
stringData:
  .dockerconfigjson: |
    {
        "auths": {
                "quay.io": {
                        "auth": "{{ .Values.quayToken }}"
                }
        }
    }
