apiVersion: v1
kind: Secret
metadata:
  name: jvm-build-secrets
stringData:
  registry.token: {{ .Values.quayToken }}
  .dockerconfigjson: |  # TODO: we should not need both these values. Given dockerconfigjson seems widely used maybe we should replace registry.token.
    {
        "auths": {
                "quay.io": {
                        "auth": "{{ .Values.quayToken }}"
                }
        }
    }
