apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - servicemonitor.yaml
  - servicemonitor_rbac.yaml

bases:
  - "../../base"

images:
  - name: hacbs-jvm-operator
    newName: jvm-build-service-image
    newTag: dev

patchesStrategicMerge:
  - namespace.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: hacbs-jvm-operator

  - patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/secret/optional
        value: true
    target:
      kind: Deployment
      name: hacbs-jvm-operator
