apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - servicemonitor.yaml
  - servicemonitor_rbac.yaml

bases:
  - "../../base"

images:
  - name: hacbs-jvm-operator
    newName: jvm-build-service-image
    newTag: dev

patchesStrategicMerge:
  - namespace.yaml
