apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../../base"

images:
  - name: hacbs-jvm-operator
    newName: quay.io/QUAY_USERNAME/hacbs-jvm-controller
    newTag: dev

patchesStrategicMerge:
  - operator-images.yaml
