apiVersion: apps/v1
kind: Deployment
metadata:
  name: hacbs-jvm-operator
  namespace: jvm-build-service
spec:
  template:
    spec:
      containers:
        - name: hacbs-jvm-operator
          env:
            - name: JVM_BUILD_SERVICE_REQPROCESSOR_IMAGE
              value: "quay.io/QUAY_USERNAME/hacbs-jvm-build-request-processor:dev"