apiVersion: jvmbuildservice.io/v1alpha1
kind: ArtifactBuild
metadata:
  name: kotlin.stdlib.jdk8.1.6.10-a9d5ad47
  namespace: test-jvm-namespace
spec:
  gav: org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10
