apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - system-config.yaml

patchesStrategicMerge:
  # see copy from openshift-ci.sh of deploy/base/system-config.yaml
  - system-config-builders.yaml
  - https://raw.githubusercontent.com/redhat-appstudio/jvm-build-service-builder-images/fbe0f42ebe3d50b16d454c95207dd15be6b5008f/image-config.yaml
