name: Container images

on:
  push:
    branches: ["main"]

env:
  IMAGE_REGISTRY: quay.io
  IMAGE_GROUP: goldmann
  IMAGE_TAG: dev

jobs:
  build:
    runs-on: ubuntu-latest

    environment: development

    strategy:
      fail-fast: false
      matrix:
        component: ["cache"]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build ${{ matrix.component }} component
        run: mvn -B package -pl ${{ matrix.component }} -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.username=${{ secrets.REGISTRY_USER }} -Dquarkus.container-image.password=${{ secrets.REGISTRY_PASSWORD }} -Dquarkus.container-image.registry=${{ env.IMAGE_REGISTRY }} -Dquarkus.container-image.group=${{ env.IMAGE_GROUP }} -Dquarkus.container-image.tag=${{ env.IMAGE_TAG }}
