name: Validate PR - Minikube Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  wait-for-images:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Images
        run: |
          while true
          do
            if ! docker pull quay.io/redhat-appstudio/pull-request-builds:jvmbuildrequestp-${{ github.event.pull_request.head.sha }} ; then
              echo "Failed to pull image 1"
              sleep 10
              continue
            fi
            if ! docker pull quay.io/redhat-appstudio/pull-request-builds:jvmcache-${{ github.event.pull_request.head.sha }} ; then
              echo "Failed to pull image 2"
              sleep 10
              continue
            fi
            if ! docker pull quay.io/redhat-appstudio/pull-request-builds:jvmcontroller-${{ github.event.pull_request.head.sha }} ; then
              echo "Failed to pull image 3"
              sleep 10
              continue
            fi
            exit 0
          done

  run-sample-project-tests:
    needs: [wait-for-images]
    runs-on: ubuntu-latest
    name: Minikube Test Sample Project
    steps:
      - uses: actions/checkout@v2
      - name: Setup Registry
        run: |
          export DEV_IP=172.16.1.1
          sudo ifconfig lo:0 $DEV_IP
          docker run -d -p 5000:5000 --restart=always  registry:2
          sudo echo '{ "insecure-registries": ["172.16.1.1:5000"] }' | sudo tee  /etc/docker/daemon.json

      - name: Start minikube
        uses: medyagh/setup-minikube@eefe3e32b8e0cbd99330ebb68c5fc2d0c2a5e68c
        with:
          cpus: max
          memory: max
          insecure-registry: '172.16.1.1:5000'
      - name: Run Tests
        run: |
          export SHELL=/bin/bash
          export QUAY_USERNAME=minikube
          export DEV_IP=172.16.1.1

          eval $(minikube -p minikube docker-env)

          docker pull quay.io/redhat-appstudio/pull-request-builds:jvmbuildrequestp-${{ github.event.pull_request.head.sha }}
          docker pull quay.io/redhat-appstudio/pull-request-builds:jvmcache-${{ github.event.pull_request.head.sha }}
          docker pull quay.io/redhat-appstudio/pull-request-builds:jvmcontroller-${{ github.event.pull_request.head.sha }}
          docker tag quay.io/redhat-appstudio/pull-request-builds:jvmbuildrequestp-${{ github.event.pull_request.head.sha }} quay.io/minikube/hacbs-jvm-build-request-processor:dev
          docker tag quay.io/redhat-appstudio/pull-request-builds:jvmcache-${{ github.event.pull_request.head.sha }} quay.io/minikube/hacbs-jvm-cache:dev
          docker tag quay.io/redhat-appstudio/pull-request-builds:jvmcontroller-${{ github.event.pull_request.head.sha }} quay.io/minikube/hacbs-jvm-controller:dev

          ./deploy/minikube-ci.sh
          make minikube-test

      - name: Archive Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: sample-report
          path: /tmp/jvm-build-service-report
  run-gav-based-tests:
    strategy:
      fail-fast: true
      matrix:
        gavs:
          - "commons-collections:commons-collections:3.2.2,org.apache.commons:commons-lang3:3.12.0"
          - "org.xerial.snappy:snappy-java:1.1.8.4,org.lz4:lz4-java:1.8.0,org.lz4:lz4-pure-java:1.8.0"
          - "io.github.jvm-build-service-test-data.maven-version-from-parent-enforce-version:maven-version-from-parent-enforce-version:1.0"
    needs: [wait-for-images]
    runs-on: ubuntu-latest
    name: Minikube GAV Matrix
    steps:
      - uses: actions/checkout@v2
      - name: Setup Registry
        run: |
          export DEV_IP=172.16.1.1
          sudo ifconfig lo:0 $DEV_IP
          docker run -d -p 5000:5000 --restart=always  registry:2
          sudo echo '{ "insecure-registries": ["172.16.1.1:5000"] }' | sudo tee  /etc/docker/daemon.json
      - name: Start minikube
        uses: medyagh/setup-minikube@eefe3e32b8e0cbd99330ebb68c5fc2d0c2a5e68c
        with:
          cpus: max
          memory: max
          insecure-registry: '172.16.1.1:5000'
      - name: Run Tests
        run: |
          export SHELL=/bin/bash
          export QUAY_USERNAME=minikube
          export DEV_IP=172.16.1.1

          eval $(minikube -p minikube docker-env)

          docker pull quay.io/redhat-appstudio/pull-request-builds:jvmbuildrequestp-${{ github.event.pull_request.head.sha }}
          docker pull quay.io/redhat-appstudio/pull-request-builds:jvmcache-${{ github.event.pull_request.head.sha }}
          docker pull quay.io/redhat-appstudio/pull-request-builds:jvmcontroller-${{ github.event.pull_request.head.sha }}
          docker tag quay.io/redhat-appstudio/pull-request-builds:jvmbuildrequestp-${{ github.event.pull_request.head.sha }} quay.io/minikube/hacbs-jvm-build-request-processor:dev
          docker tag quay.io/redhat-appstudio/pull-request-builds:jvmcache-${{ github.event.pull_request.head.sha }} quay.io/minikube/hacbs-jvm-cache:dev
          docker tag quay.io/redhat-appstudio/pull-request-builds:jvmcontroller-${{ github.event.pull_request.head.sha }} quay.io/minikube/hacbs-jvm-controller:dev

          export GAVS=${{ matrix.gavs }}

          ./deploy/minikube-ci.sh
          make minikube-test
      - name: Archive Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: matrix-report
          path: /tmp/jvm-build-service-report
